### ISSUE TITLE
Binary has no icon

### ISSUE THREAD

**Issue by croxxx** [manicdigger/manicdigger#1]
In previous versions the Binaries had an icon.
This is missing in latest release.

**Comment by croxxx** [comment]
Latest version (2015-08-22) seems to have some sort of icon displayed in taskbar:
![2](https://cloud.githubusercontent.com/assets/5447834/9473260/24c1bc6c-4b5a-11e5-983a-947b2b18c01c.png)

Icon in explorer is still missing:
![1](https://cloud.githubusercontent.com/assets/5447834/9473266/291d1324-4b5a-11e5-89c0-7b74bf6ba763.png)

**Comment by joshi1999** [comment]
I'd tried to reproduce the bug:
1. Downloaded Binary: No icon (taskbar and folder) (2015-10-14a)
2. Recompiled the game, putted in a zip-folder, putted it out and tested: Normal icon (taskbar and folder) (Actually and 2015-10-14a)

croxxx: did you download the binary, or did you recompile it?

**Comment by croxxx** [comment]
I used the normal version back then but I'm quite certain it was a cached icon of some sort as I've seen that multiple times for different applications now.

**Comment by MrRar** [comment]
The icon is also missing from the Javascript version as well.
![capture](https://cloud.githubusercontent.com/assets/16406771/13723885/478898da-e838-11e5-9d47-2188cee9e24d.PNG)

**Comment by croxxx** [comment]
Web version updated in bcb42039ff6cc7fb7131e55eba5ab8a4708b8220
Installer should now create a desktop icon with proper image.

**Comment by croxxx** [comment]
Seems to be fixed with 1f20ace1b5a918faeb3a7933f2d1cb5b6fd17bb1.
Compiled on Xubuntu 16.04, icon was displayed correctly on Windows 10.
