### ISSUE TITLE
Raster rendered on blocks

### ISSUE THREAD

**Issue by TobiMob** [manicdigger/manicdigger#155]
I did a clean checkout from the [master branch](https://github.com/manicdigger/manicdigger/commit/639024d62018c1dcda3ac2fc74c6ba5c61ec4742), but it renders me a nice raster on the blocks.
A older version works fine on the same machine, so the graphic drivers should be fine.

Any ideas?

![renderbug](https://cloud.githubusercontent.com/assets/9436771/5607415/710d65b4-945b-11e4-9f9e-e7eaed1da9b3.jpg)

**Comment by croxxx** [comment]
Hi TobiMob,

I guess this is a result of `data\local\grass.png` being used instead of `data\public\blocks\Grass.png`
Try deleting that file for testing.
This file is used in Mob Editor as floor texture, but normally not in the main game.

**Comment by TobiMob** [comment]
Hi,

that helped with the white lines on grass-blocks.
But I still get a 1 pixel wide space between blocks

![renderbug](https://cloud.githubusercontent.com/assets/9436771/5618042/210a80b4-9515-11e4-8b90-ba1395196374.jpg)
![renderbug2](https://cloud.githubusercontent.com/assets/9436771/5618044/22cb4d8e-9515-11e4-9d98-113022b8821b.jpg)

**Comment by PrincessPirate** [comment]
I have this problem on some servers, but rejoining fixed it. Should it be deleted from the main game to avoid future conflict?

**Comment by croxxx** [comment]
@TobiMob: Are you using integrated graphics? Intel HD or similar? That's where I last noticed that problem. For me using an AMD card everything looks fine.
@PrincessPirate: I guess renaming the file would be enough. As I said: it's used by monster editor.

**Comment by TobiMob** [comment]
Hi,
@croxxx : Switching from integrated graphics to the NVIDIA card did the trick :)
Strange that it worked fine with a older build.

I may look into that, after I finished my current branch. But for now it works fine.
