### ISSUE TITLE
Building Always Fails

### ISSUE THREAD

**Issue by EmilSayahi** [manicdigger/manicdigger#159]
Whenever I build, I get an error in MainMenu.ci.cs.
![errorbuild](https://cloud.githubusercontent.com/assets/5004276/5770775/5c824262-9cfe-11e4-8132-ae501b24e415.png)

**Comment by TobiMob** [comment]
Not really MD related :/

Anyway, you broke it there -> [Emil-Block-Game Commit](https://github.com/EmilSayahi/Emil-Block-Game/commit/9a4a667197f044ac8da21dc174ffdf794d79e242)

**Comment by croxxx** [comment]
I have to agree with @TobiMob here.
Please only open issues for problems in this repositories' code.

**Comment by EmilSayahi** [comment]
I opened this issue as the two games are very, very similar in code.

**Comment by TobiMob** [comment]
I'm really sorry, but that is just not how it works.
You can't go to the linux main branch and open an issue: "My SteamOS crashes".

The main problem is, that those two repositories have copletly different commit histories.
So we have no real way to know, which changes/bugfixes are present in both repositories.

Second, the issue tracker is used to improve the code of [this](https://github.com/manicdigger/manicdigger) particular repositorie.
If a bug was added in a other repositorie, [this](https://github.com/manicdigger/manicdigger) repositorie is not affected, and won't be improved if that bug gets fixed.
So the issue becomes a "general coding help", which is just not what the issue tracker is made for.
For such thing http://stackoverflow.com/ exists.

Anyway, you broke it there -> [Emil-Block-Game Commit](https://github.com/EmilSayahi/Emil-Block-Game/commit/9a4a667197f044ac8da21dc174ffdf794d79e242)
Above Line 2158

**Comment by EmilSayahi** [comment]
Okay, thanks. Plus, I fixed it. Thanks for the information and I hope you have a great day. You're a big help! :) :+1:
