### ISSUE TITLE
New BlockId Problems

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#162]
I have created a tiny, simple mod for a new blocktype and I encountered a problem.
In the mod, I simply created a new block "Test" of BlockID 290. I first told it to re-retrieve the blocktype, as expected, it returned "Result: 290 - Test"

Here's the problem:
Upon restarting the server, all blocks in the world that has a blockid greater than 255 gets looped back around: EX 256 becomes 0, 257 becomes 1, 258 becomes 2 etc... Blocks in inventory are NOT affected by this. Blocks in hand are NOT affected by this. The blocks in the world, however, are. Also the m.SetBlock(x, y, x, block); does nothing at all if it is greater than 255. The strange thing is that you can place a block of higher blockid in the world successfully as a player. But as stated earlier, a server restart loops the blockid down.

**Comment by TobiMob** [comment]
It looks like BlockId is handled as int(?) at runtime, but stored as byte.
That would explain the overflow after loading.

I guess BlockId > 255 is not working at the moment.
But a expert should give a statement to this issue :)

_ManicDiggerLib/Server/ChunkDb.cs_
```cs
public struct DbChunk
{
    public Xyz Position;
    public byte[] Chunk;
}
```

**Comment by croxxx** [comment]
Indeed, originally the MD save format was only intended for 256 different blocks.
Blocks should be handled as **ushort** now, though.
If I remember this right, server chunk format was changed...
```csharp
[ProtoContract()]
public class ServerChunk
{
    [ProtoMember(1, IsRequired = false)]
    public byte[] dataOld;
    [ProtoMember(6, IsRequired = false)]
    public ushort[] data;
    [ProtoMember(2, IsRequired = false)]
    public long LastUpdate;
    [ProtoMember(3, IsRequired = false)]
    public bool IsPopulated;
    [ProtoMember(4, IsRequired = false)]
    public int LastChange;
    public bool DirtyForSaving;
    [ProtoMember(5, IsRequired = false)]
    public List<Monster> Monsters = new List<Monster>();
    [ProtoMember(7, IsRequired = false)]
    public int EntitiesCount;
    [ProtoMember(8, IsRequired = false)]
    public ServerEntity[] Entities;
}
```
Maybe @exemd can enlighten us with some details? ;)

**Comment by exemd** [comment]
@TobiMob struct DbChunk is fine, at this point it's already serialized with protobuf - it's binary data, not voxels.

This is wrong:
https://github.com/manicdigger/manicdigger/blob/6249c3eb27e69eff4fc24a61349251fe220cba50/ManicDiggerLib/Server/ServerMap.cs#L72

**Comment by superstorm192** [comment]
Actually m.SetBlock(x,y,z,w); works perfectly to place a blockid > 255. It is m.GetBlock(x,y,z,w); that returned the looped number.
