### ISSUE TITLE
/give has a bug

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#167]
I just found this bug on Isiah's Super Sessy Server. Let's assume player B has a stack of 22 Wood in his inventory at location(1,2).
Player A types: /give {B} Wood 50
Player B looks into his inventory to find that at (1,2) there is a stack of 50 Wood. It should be a stack of 72. 22(starting number) + 50 (giving number) = 72(ending number).
Player B can not find a total of 72 Wood, the stack of 22 became 50 instead.

My thoughts are that somewhere in the code, it fsearches for a slot with the blockid. Once found it changes it to set(GIVE) when it should set(GET CURRENT AMOUNT + GIVE )

**Comment by TobiMob** [comment]
good guess: [ServerCommand.cs](https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/Server/ServerCommand.cs#L1381)

```cs
//changing it from this
currentItem.BlockCount = amount;
//to that
currentItem.BlockCount += amount;
```
would give the result you expected.
I would also expect a "give"-command to always give something and don't take something away.

A question to the others:
Does anything rely on this behavior of the give-command, or can it simply be changed?

**Comment by croxxx** [comment]
It should be safe to change as it's only used in non-creative game mode as far as I know...

**Comment by TobiMob** [comment]
If nothing speaks against it, would be cool if somebody volunteers.
I am a bit lazy to fork for 3 lines :p
