### ISSUE TITLE
Threads never closing?

### ISSUE THREAD

**Issue by Glitchfinder** [manicdigger/manicdigger#173]
It looks like this game starts a lot of threads that never get closed, even when going back to the title screen. Could this have anything to do with the memory leaks, chunk unloading issues, and other instabilities?

**Comment by croxxx** [comment]
I have to admit I never monitored client threads myself. At least with multiplayer I got no problems when switching servers.
The only thing I know can be strange is quitting from singleplayer mode...

The client memory leak comes from received chunks never being unloaded by client. Currently client stores everything it has ever seen. I started optimizing this a while ago but didn't have the time lately.

**Comment by TobiMob** [comment]
I had a brief look into it.
On Windows with release build (no debugger attached) i had about 35 Threads running
It looks like ~3 of the threads run MD-code, 
~10 run unknown .net code, 
and the rest seems unmanaged.

The number of threads increases with the first login on a server.
After a disconnect/reconnect they jump up and down a bit, but don't grow above 37.

Threads running unknown code are rarely a problem. Unless they grow in number.
If you find a way to spawn a great amount of threads, that is a problem!

So unless somebody finds a way to create big amounts of threads, 
I would not suspect the threads to be responsible for memory or stability problems.

**Comment by croxxx** [comment]
@Glitchfinder Could you please provide more details on when exactly this does happen and how to reproduce the issue?

**Comment by Glitchfinder** [comment]
I may have been mistaken. I don't have a live profiler capable of detailing the threads. I was just working through the code when I realized I couldn't find a single way to explicitly close a thread aside from killing the process. I probably am mistaken, I'm not familiar enough with the codebase to be certain I didn't miss anything.

**Comment by exemd** [comment]
It's caused by ThreadPool.
It's not a problem. Maybe a bit too many threads are reserved, but it's better to have too many than too few.

        System.Threading.ThreadPool.SetMinThreads(32, 32);
        System.Threading.ThreadPool.SetMaxThreads(128, 128);

https://github.com/manicdigger/manicdigger/blob/703f060a5c16ccbff6eb4b478cc760cb287f0a66/ManicDiggerLib/Client/Misc/PlatformNative.cs#L207

**Comment by croxxx** [comment]
In this case I think this can be closed?
