### ISSUE TITLE
OnLoad issue in new release.

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#174]
The server seems to not do anything related to the OnLoad command. It has already caused one of my newest mods to be rendered useless for the time being, and a secondary mod that generates a list of block ids also refused to run.
```
m.RegisterOnLoad(OnLoad)
```
```
void OnLoad()
{
    System.Console.WriteLine("This mod's OnLoad Function worked.");
}
```
For example, a cs containing this, along with the basics, would NOT write the message in the console as if it never even was told to.

**Comment by croxxx** [comment]
Hm, looking at the code both `RegisterOnLoad()` and `RegisterOnLoadWorld()` are called.
I don't have the time to further look into this right now. Maybe someone can try to reproduce this?

**Comment by superstorm192** [comment]
Below is a full mod that can be copied into a cs file and ran instantly.
If "Sucess in calling the OnLoadTester mod." does not appear in your server console, the OnLoad() function was not called.
--
using System;
namespace ManicDigger.Mods
{
    public class OnLoadTester : IMod
    {
        public void PreStart(ModManager m)
        {
        }
        public void Start(ModManager manager)
        {
            m = manager;
            m.RegisterOnLoad(OnLoad);
        }
        ModManager m;
        void OnLoad()
        {
            System.Console.WriteLine("Sucess in calling the OnLoadTester mod.");
        }
    }
}
--

**Comment by croxxx** [comment]
Hm, I do currently not have the time to fully test that.
But I noticed the savegame being loaded much earlier in this version.
Maybe it's simply that the savegame is being loaded before the Mods are compiled?

**Comment by superstorm192** [comment]
A strange thing is I found another way that seems to function the same as ```m.RegisterOnLoad(OnLoad);```; by replacing ```m.RegisterOnLoad(OnLoad);``` with only this simple line ```OnLoad();```, it seems to function as if nothing was wrong with it at all, which there may not be.

```
using System;
namespace ManicDigger.Mods
{
    public class OnLoadTester : IMod
    {
        public void PreStart(ModManager m)
        {
        }
        public void Start(ModManager manager)
        {
            m = manager;
            OnLoad();
        }
        ModManager m;
        void OnLoad()
        {
            System.Console.WriteLine("Sucess in calling the OnLoadTester mod.");
        }
    }
}
```

**Comment by croxxx** [comment]
Yeah, for own Mods I also use that method.
It had a reason I did that but I can't remeber it right now...

Did you test both methods?

**Comment by superstorm192** [comment]
Yes, with new release ```m.RegisterOnLoad(OnLoad);``` is never called, but replacing that line with ```OnLoad();``` works as expected with the new release.

**Comment by croxxx** [comment]
This does also affect builtin mods.
Most importantly the **BuildLog**. Changes are not loaded when server is restarted!
