### ISSUE TITLE
Text in new release

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#175]
When typing, the text is hidden behind the health bar and material slot bar.

**Comment by croxxx** [comment]
Yep. That's right.
Probably only an issue of draw order.

**Comment by superstorm192** [comment]
The text is in front of dialogs. It should be inventory under text under dialogs. It currently is dialogs under inventory under text.

**Comment by croxxx** [comment]
Fixed in 0ac9916a8ecce20e6557000deb120d5b371b8518
