### ISSUE TITLE
activematerial2.png not working in new release.

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#176]
activematerial2.png found in data/public/inventory seems to not be the priority and is not used, instead, the red outline box is default: activematerial.png found in data/local/gui

**Comment by croxxx** [comment]
It seems that `activematerial2.png` simply is not used anymore.
Default will be overwritten when naming the public file `activematerial.png`.

**Comment by superstorm192** [comment]
Ok that works but there is a problem, the texture sizes do not match up. A 64x64 image with a red rectangle the size of the cell(48 pixels) is actually drawn LARGER than the cell when presented in game: using Pant.exe i deduced the size of the cell as 48x48 pixels, while the 48x48 info was larger than 48x48..

I have located the problem in the sourcecode myself at ```ManicDiggerSource/ManicDiggerLib/Client/Mods/GuiInventory.ci```
Original
```
460:        game.Draw2dBitmapFile("activematerial.png",
461:            MaterialSelectorStartX() + ActiveMaterialCellSize() * game.ActiveMaterial,
462:            MaterialSelectorStartY(), ActiveMaterialCellSize() * 64 / 41, ActiveMaterialCellSize() * 64 / 41);
```
Fixed
```
460:        game.Draw2dBitmapFile("activematerial.png",
461:            MaterialSelectorStartX() + ActiveMaterialCellSize() * game.ActiveMaterial,
462:            MaterialSelectorStartY(), ActiveMaterialCellSize(), ActiveMaterialCellSize());
```
New Png image to go along with fix at ```Manic Digger/data/local/activematerial.png```.
Scroll over for additional info.
![activematerial](https://cloud.githubusercontent.com/assets/10588108/6429515/e712e3e4-bf9c-11e4-894a-00fe300b2c71.png "Name:activematerial.png, Dimensions:64x64, Size:358 bytes,")
