### ISSUE TITLE
Default.cs causes duplicate crafting recipe entries.

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#179]
Because of the change from ```Default.cs``` to ```Core.cs```, ```CoreBlocks.cs``` and ```CoreCrafting.cs``` along with the fact that ```Default.cs``` does not get deleted on ```Setup.exe``` method, along with another fact that most mods created by users  have the line ```m.RequireMod("Default");``` in their mods, it would be easier to change ```Default.cs``` than to change all of the custom mods that users need. This new ```Default.cs``` must still exist.

Filename: ```Default.cs```

```
using System;
namespace ManicDigger.Mods
{
    public class Default : IMod
    {
        public void PreStart(ModManager m)
        {
            m.RequireMod("Core");
            m.RequireMod("CoreBlocks");
            m.RequireMod("CoreCrafting");
        }
        public void Start(ModManager manager){ }
    }
}
```

**Comment by croxxx** [comment]
I did split `Default.cs` for easier addidtion and modification of gamemodes.
I'm aware that this requires a minimal change in some Mods. I also noticed, that many mods include the requirement for `Default.cs` but actually never using anything from it.

I'm not sure if this should be included by default, but it seems like a nice workaround.
