### ISSUE TITLE
Looping fallloop audio in new release

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#180]
You join a server, notice you are in the air and falling, then press your ```[freemove]``` key to stop. But then you hear the ```fallloop.ogg``` continuing to repeat forever and ever and you are driven crazy until you press the ```[freemove]``` key a few more times really fast to stop the annoying sound that only stops when you hit the ground (which can't happen in freemove, even when you touch a block, the same sound keeps playing in a certain stationary spot.)

**Comment by croxxx** [comment]
I noticed that, too.
@exemd and I talked about maybe removing the falling sound completely. Thoughts on this?

**Comment by superstorm192** [comment]
I think it should stay, everyone is used to hearing this sound when falling.

**Comment by croxxx** [comment]
@superstorm192 I gotta admit that I don't really like it...

**Comment by zbierajewski** [comment]
I too am not too fond of it. but maybe keep the ground-hit sound?

**Comment by croxxx** [comment]
The "ground-hit" sound is actually the death sound :smile: 
But I get what you mean. will look into this when it fits in.

**Comment by zbierajewski** [comment]
Yes lol. The death sound.
