### ISSUE TITLE
Trees can no longer grow in new release

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#181]
Since the name of the trees got changed and new ones added, ```VegitationGrowth.cs``` no longer has the capability to allow trees to grow. I am currently working on a version of ```VegitationGrowth.cs``` that will incorporate the new changes with tree names.

Finished mod will be added to mods directory in the forums upon completion. (Done)

**Comment by croxxx** [comment]
I have to admit that I overlooked this when implementing new blocktypes.
Already posted a note here: #150

**Comment by superstorm192** [comment]
The completed VegetationGrowth.cs can be found here: [```VegetationGrowth.cs```](http://manicdigger.sourceforge.net/forum/viewtopic.php?f=17&t=4449 "VegetationGrowth.cs fix for update 2015-2-17")

**Comment by croxxx** [comment]
Fixed in 8d941ff0e2448f8193c1c907c8900105751e55f9
Now 3 different tree types are generated.
Maybe I'll merge this with TreeGenerator.cs at some point.
