### ISSUE TITLE
Transparent Textures Problem

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#184]
The Transparency below 50% is cut off and is 100% transparent instead of what it should be. There are also visual errors where the opposite side of the block does not show when transparency is above 50%(however other sides do, which look awesome by the way.)
```
1: Actual Transparent Png
2: Color-Only Png
3: Alpha-Only Png (Red)
```
![atestc](https://cloud.githubusercontent.com/assets/10588108/6361569/48fd64c8-bc49-11e4-8332-a4dfcf20b12d.png) ![atest](https://cloud.githubusercontent.com/assets/10588108/6361607/a1d9f85e-bc49-11e4-94d1-d5b902a14d25.png) ![atesta](https://cloud.githubusercontent.com/assets/10588108/6361609/a48e1c4c-bc49-11e4-8830-55e4fb399e7f.png)
```
In-Game snapshot of block using Transparent Png.
```
![2015-02-24_17-30-04](https://cloud.githubusercontent.com/assets/10588108/6361835/f0f67d20-bc4b-11e4-9def-ef80d38c7b74.png)

**Comment by croxxx** [comment]
Transparency being cut off is a known issue.
There was a reason for doing that but I can't remember what @exemd told me about that...

Flipped texture on one side as a bug that's also described in #182

**Comment by croxxx** [comment]
Transparency issues see: #165
