### ISSUE TITLE
public server textures applied to other servers with no public textures

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#186]
I recommend that when joining someone elses server that is lacking files in the ```data/public/inventory/``` directory to use the texture from my server's ```data/local/inventory/``` instead of ```data/public/inventory/``` directory, because it makes me feel like other servers are taking my texture that i haven't uploaded and it creeps me out.

Files of focus:
```
activematerial.png
inventory.png
materials.png
mousecursor.png
target.png
etc...
```

**Comment by croxxx** [comment]
This is exactly what is currently done.

Local files (`data/local`) are used as stored on your PC.
Then files present on the server (`data/public`) are used to overwrite the already loaded ones.
That way a server also can supply only parts of all needed textures without any missing.

Only thing that may occur is a little issue with textures when switching servers without exiting the game.

What exactly is the problem here?

**Comment by superstorm192** [comment]
The problem is when i go on someone else's server ```Example Server 1```, i see MY server's ```Superstorm's Survival Server```'s textures if there is no files in ```Example Server 1```'s public file. I would expect to see ```Example Server 1```'s local files.
Basically if I go to ```Example Server 1``` and they don't have any textures, i see MY ```Superstorm's Servival Server: data/PUBLIC/inventory``` instead of ```data/LOCAL/inventory``` If their server has no PUBLIC textures, it shows MY PUBLIC textures when it should show THEIR OR MY LOCAL textures.

**Comment by croxxx** [comment]
Textures are split into `local` and `public` folders to save bandwidth.
As all files in `local` folder are ignored by the server and **not** sent to clients.
Client handles all textures not sent by server by using their counterparts installed locally.
The special part is that a server may supply files normaly in `local` as `public` so clients use them (e.g. skyspheres)

**This is intended behaviour.**

*If you are running a server I recommend to run it from a separate folder than your regular game. That way you can easily distinguish client and server files. Also it prevents this problem from happening.*

**Comment by superstorm192** [comment]
I apologize for making a big deal about this, I have downloaded another manic digger in a folder directly in ```Program Files/Manic Digger``` while my server is in ```Program Files/A/Manic Digger```. The issue seems to be resolved as you said, thank you for this suggestion.
