### ISSUE TITLE
activematerial.png is not aligned correctly.

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#188]
Ok that works but there is a problem, the texture sizes do not match up. A 64x64 image with a red rectangle the size of the cell(48 pixels) is actually drawn LARGER than the cell when presented in game: using Pant.exe i deduced the size of the cell as 48x48 pixels, while the 48x48 info in the png image showed as a size of 52x52 in game.

I have located the problem in the sourcecode myself at ```ManicDiggerSource/ManicDiggerLib/Client/Mods/GuiInventory.ci```
Original
```
460:        game.Draw2dBitmapFile("activematerial.png",
461:            MaterialSelectorStartX() + ActiveMaterialCellSize() * game.ActiveMaterial,
462:            MaterialSelectorStartY(), ActiveMaterialCellSize() * 64 / 41, ActiveMaterialCellSize() * 64 / 41);
```
Fixed
```
460:        game.Draw2dBitmapFile("activematerial.png",
461:            MaterialSelectorStartX() + ActiveMaterialCellSize() * game.ActiveMaterial,
462:            MaterialSelectorStartY(), ActiveMaterialCellSize() * 64 / 48, ActiveMaterialCellSize() * 64 / 48);
```
New Png image to go along with fix at ```Manic Digger/data/local/activematerial.png```.
Scroll over for additional info.
![activematerial](https://cloud.githubusercontent.com/assets/10588108/6429515/e712e3e4-bf9c-11e4-894a-00fe300b2c71.png "Name:activematerial.png, Dimensions:64x64, Size:358 bytes,")

Same Png compressed using [TinyPng](https://tinypng.com/ "TinyPNG - Compress PNG images while preserving transparency")
![activematerial 2](https://cloud.githubusercontent.com/assets/10588108/6657076/0d7ff068-cb0e-11e4-99f2-6af35dca1a43.png "Name:activematerial.png, Dimensions:64x64, Size:117 bytes")

**Comment by croxxx** [comment]
I also noticed this when updating to the newest version.
In my opinion the "best variant" would maybe be just using the full 64x64?
The GUI is scaled depending on client and screen resolution anyway...

**Comment by superstorm192** [comment]
I disagree on using the entire 64x64 because the default gui size shows 48x48. Not only that, I have discovered a unique use for the extra space at the bottom, you can see it on my server.
