### ISSUE TITLE
Player Pusher Improvement

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#204]
When you are teleported using `m.SetPlayerposition();` there is an invisible force that pushes the player away from it. I am assuming that this is the new player pusher update. Unfortunately i noticed that this force seems to remain there for i dont know how long. I suggest that the player pusher force dissapears 2 to 5 seconds after it is made. This length of time should be enough to push the player out of the corner and not long enough that when the player moves back through it, the player isnt pushed back anymore by a now annoying invisible force. Also, it pushes players using noclip.

Question: With current released version, can this feature be manually disabled?

Also, can this function only be ran if the player is in a corner so teleportation will remain smooth (I recently made a portal mod)

**Comment by croxxx** [comment]
I also noticed this happening lately. It definitely is caused by player pushing not working as intended.

The current version offers a variable in `ServerConfig`.txt to turn player pushing off.
Simply change the value at the bottom of the file so it says:
```xml
<EnablePlayerPushing>false</EnablePlayerPushing>
```
