### ISSUE TITLE
Scrolling

### ISSUE THREAD

**Issue by joshi1999** [manicdigger/manicdigger#207]
When I scroll  with my mouse in the inventory and serverlist (ingame) there are 2 steps instead of 1
Is it beacause Windows 10?

**Comment by croxxx** [comment]
Working normally on Windows 7.
As I don't have Windows 10 currently, can anyone else confirm this?

**Comment by Nisc3d** [comment]
Yes. I can confirm this.

**Comment by croxxx** [comment]
Could you test if the issue persists in this version (2015-09-14):
https://github.com/manicdigger/manicdigger-builds/blob/gh-pages/ManicDiggerLatestBinary.zip

**Comment by Nisc3d** [comment]
It's not fixed in this version.

**Comment by joshi1999** [comment]
Hey guys,
after some experiments, I found the solution for this problem :)
Start -> Settings -> Equipment settings -> Mouse and ouchpad -> Inactive Windows (scroll) from on to off. Finish :)

**Comment by croxxx** [comment]
Nice find!

As this is a proper solution I will not implement a workaround (those would all have included ignoring some "user input"). Closing this.

Technical background:
*On Windows 10 two mouse events seem to be fired when this function is enabled. This even occurs when the window is focused.*
***
Maybe there should be a FAQ section somewhere to look up things like this.

**Comment by joshi1999** [comment]
like the wiki ? :)

**Comment by croxxx** [comment]
Listed as Issue in opentk/opentk#488.

**Comment by croxxx** [comment]
Implemented a workaround in ec70f7e2ae2c52cb48a8b4394181f18f462218e5.
This discards all MouseWheel events for 10 milliseconds after the last one was fired.

**Comment by varon** [comment]
This was addressed properly upstream. https://github.com/opentk/opentk/pull/536
