### ISSUE TITLE
Unable to Send Heartbeat Annoying

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#208]
When sorceforge is not available for some reason, the server spits out like 23 lines of error feedback. I suggest this gets filtered through a try catch and send "Unable to send heartbeat: Hosting server unavailable" which is only one manageable line.

**Comment by joshi1999** [comment]
Cool idea! :D

But is it useful, if you don't know why?

**Comment by croxxx** [comment]
I guess it'd be an option to catch just the corresponding network exceptions and shorten the error message.
