### ISSUE TITLE
Server does not have all privileges

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#210]
On creation of a new privilege for a mod, the Server Console does not automatically get said privilege and there is no way to set it in the configuration files, is there? Should the Server Console have all privileges automatically?

**Comment by croxxx** [comment]
The server console has all default privileges.
Also, in Mods `RegisterPrivilege()` can be used.
You can look up the usage in the default mods.
https://github.com/manicdigger/manicdigger/blob/master/ScriptingApi/ModManager.cs#L196

**Comment by superstorm192** [comment]
When I am in Server console and type in "/playsound {sound}" (from my mod) that uses `if (!m.PlayerHasPrivilege(player, "serverblocks"))` which is registered with `m.RegisterPrivilege("serverblocks");` I still get the message saying that i dont have privileges for that, so something's wrong somewhere.

**Comment by croxxx** [comment]
I see, this problem seems to be caused by the introduction of Server systems.
Working on a fix...
