### ISSUE TITLE
Block taking/placing with gun not working.

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#224]
When a gun is in hand, the blocks that are in range get highlighted, but when left click, it only shoots the gun, and the block is not taken. Right click only toggles ironsights, and the block is still not taken(or placed in this sense).

*On the plus side Using[E] blocks works perfectly while armed :D*

**Comment by croxxx** [comment]
This is exactly what is intended to happen.
The player should be able to use but not destroy blocks accidentally.

**Comment by superstorm192** [comment]
Oh, ok, makes sense now. I just misinterpreted the statement that we would be able to take/destroy blocks also. Thank you for the swift reply :D
