### ISSUE TITLE
Suggestion: Dialog buttons

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#225]
I am thinking add a `.Clickable` property to dialogs used like this.

```
Widget button = new Widget();
button.X = -16;
button.Y = -16;
button.Width = 32;
button.Height = 32;
button.Image = "IronOre";
button.Id = "dialogbuttonclickironore";
button.Clickable = true; //NEW PROPERTY
```

If this part of the dialog is clicked from `X to X+Width` and `Y to Y+Height` and the `this.Clickable = true;` then call the same function as `this.ClickKey = (char)##` does: `m.RegisterOnDialogClick();`.

**Comment by croxxx** [comment]
I assume you mean that buttons should be clickable using the mouse.

If I remember correctly signs implemented such behaviour:
- https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/Server/Systems/Sign.cs
- https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/Server/Systems/PermissionSign.cs

I might be wrong, but I think they do.

**Comment by superstorm192** [comment]
Yes, you assumed correct. I'm going to look deeper into the code... hm... speaking of, i just now noticed the use of deeper level code `server.something` that i couldn't find a way to get working (but now i know it is possible and can start experimenting). I will inform you if i find out how to get mouse clicks to work.

**Comment by croxxx** [comment]
I think you might have gotten that wrong.
What I linked is not available through Mod API.

**Comment by superstorm192** [comment]
Oh... what exactly is (char)13?

**Comment by superstorm192** [comment]
I just now noticed that all widgets (not dialogs) that have a `Widget.ClickKey` assigned can also be clicked with the mouse, even if the char is not a "valid" one, which solves the problem for now.
