### ISSUE TITLE
Tiny bug. Compass.

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#228]
```
m.SetBlockType(151, "Compass", new BlockType()
{
	AllTextures = "Compass",
	TextureIdForInventory = "CompassInventory",
	DrawType = DrawType.Plant,
	WalkableType = WalkableType.Solid,
	Sounds = solidSounds,
});
```
The ```Alltextures = "Compass",``` references to a nonexistent png file. Since Compasses would not normally be found in the world, simply changing it to ```AllTextures = "CompassInventory",``` and removing the next line should tidy things up, UNLESS, the png file ```Compass.png``` itself never made it to the download file.

I found this tiny bug when working on a new mod that assigns every valid blockid a unique color that is visually acceptable. (Grass is green, Dirt is brown, etc...)

**Comment by croxxx** [comment]
It seems that detail slipped me when fixing the compass display here: https://github.com/manicdigger/manicdigger/commit/4791e9be665f637b1d9a7d4f13f2f0af47a40c49
As the compass is not placeable, it shouldn't make that much of a difference.
I will change this in an upcoming commit.
