### ISSUE TITLE
Dialog font and color not working.

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#231]
`new DialogFont("Arial", 8f, DialogFontStyle.Regular)`
changing the size `8f` works fine.
changing the `DialogFontStyle.Regular` works fine as well,
but changing the actual font `"Arial"` does not work. Comparing two different `DialogFont`s proves that they are the exact same font, even though they should not be.
The color of the font does not work either. The font is always black (except through `&0-&f` color codes).

```
static DialogFont NormalFont = new DialogFont("Verdana", 8f, DialogFontStyle.Regular);
static DialogFont NormalFont2 = new DialogFont("Arial", 8f, DialogFontStyle.Regular);
---lots of code---
widgets.Add(Widget.MakeText(blockamount, NormalFont, theX + 16 + 48*xi, theY + 16 + 48*yi, Color.FromArgb(255,255,0,0).ToArgb()));
widgets.Add(Widget.MakeText(blockamount, NormalFont2, theX + 16 + 48*xi, theY + 32 + 48*yi, Color.FromArgb(255,255,0,0).ToArgb()));
```

![image](https://cloud.githubusercontent.com/assets/10588108/11882804/527273f8-a4d4-11e5-8b79-6f5c67a7fc80.png)

EDIT: noticed that i didn't have `using System.Text;` but that still did not solve the issue.

**Comment by croxxx** [comment]
Might be related to this:
- https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/Client/Mods/Dialog.ci.cs#L244
- b7874d0e466b753957f4de075f92a7cee08d0a7e

It probably was broken (or not noticed before) when default color was changed

**Comment by croxxx** [comment]
After applying the changes made in fc65a18b3f9b3221f99a3e10cbfcd9fac9ef4a91 this is now possible.
![2017-03-04_12-54-21](https://cloud.githubusercontent.com/assets/5447834/23578564/2079494a-00da-11e7-9426-3edc52d3fda4.png)
