### ISSUE TITLE
Dialogs and the escape key

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#232]
Having esc key get out of all `m.IsModal();` dialogs is pretty convenient. However, I think it needs to also call the `widget.ClickKey` because i need to set a variable to null when a player hits esc from a certain dialog, and this cannot happen when the esc key is not registered in `OnDialogClick();` for the dialog when it is pressed.

Either that or a function to see if a certain dialog is showing (not null) on a certain player like `m.IsDialogOpen(player, dialogid);`.

**Comment by croxxx** [comment]
From what I recall you can do that by assigning it the ID `"Esc"`.
You can find the implementation details here: https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/Client/Mods/Dialog.ci.cs#L106
`PlayerList.cs` has an example of usage:
```csharp
var wesc = Widget.MakeSolid(0, 0, 0, 0, 0);
wesc.ClickKey = (char)27;
wesc.Id = "Esc";
widgets.Add(wesc);
```

**Comment by superstorm192** [comment]
It worked, thank you. Quick question: is there a way to get a widget to follow the mouse, or maybe override one already connected to it like the `m.GetInventory(player).DragDropItem` widget, or maybe make the dragdrop block show in `Dialog.IsModal()` also? I am so close to making an actual chest mod now, i'm only onedragdrop widget away from a true one.

**Comment by croxxx** [comment]
No, that's not possible as it's done client-side.
If you are interested in doing so, you might want to have a look at clientside modding as well.
That is more complex than server mods, though.

**Comment by superstorm192** [comment]
So is it possible to make a new mod in the client format or do I have to recompile the entire game each time I change something?

**Comment by croxxx** [comment]
Recompiling it is.
