### ISSUE TITLE
WidgetType.TextBox

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#235]
I have recently found an already partially implemented text box system for the modding api. When put in game it looks like a normal piece of text until you click on it. When you do, a `_` appears after the string and your keystrokes are turned into letters like a normal text field.

Issue Number1: All Dialog ClickKeys are still registering while in the text box. For example, if `e` closes the window, typing `e` into the text box will close the window.

Issue Number2: Backspace does not work in this text box. All other typeable characters do work, including shifting to capitalise letters. `[]\;',./-=_+{}|:"<>?` also work. Alt ### also successfully inserts a unicode character(only tested normal letter s (Alt-155)).

Also, how do you send the text through a variable. I have also seen a `void RegisterOnDialogClick(ModDelegates.DialogClick a);` that does this but I haven't really experimented with this.
- [x] Allow Backspace to work
- [ ] Block keystrokes from registering `Widget.ClickKey` while inside a text field.
- [x] `RegisterOnDialogClick(DialogClick dialogargs)` working to pass textbox value.

**Comment by superstorm192** [comment]
- [ ] Allow Backspace to work
- [ ] Block keystrokes from registering `Widget.ClickKey` while inside a text field.
- [ ] Enter key registers with input inside textbox for variable magiks.

**Comment by croxxx** [comment]
Textbox response can be used when registering with `RegisterOnDialogClick2(DialogClick2 dialogargs)` as of 18063abad55dce12d3152aef40f835fddedd23d3
This method offers more options than the old one and should be used in the future.
