### ISSUE TITLE
m.RegisterCheckOnBlockDelete() - Question

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#238]
`m.RegisterCheckOnBlockDelete()` is missing the return variable `oldbock`.

```
     m.RegisterOnBlockDelete(int player, int x, int y, int z, int oldblock);
m.RegisterCheckOnBlockDelete(int player, int x, int y, int z); //missing oldblock
```

Upon further thinking I am not 100% sure it is actually needed anyways. At one time I needed that functionality for something, but cannot remember what exactly for. Maybe the main question is if this was omitted intentionally or by accident?

**Comment by croxxx** [comment]
This is intended.

As the check method is called **before** any action is taken, you can simply use `m.GetBlock()` to determine the current block.
The OnDelete function on the other hand is called **after** the block has been deleted and therefore supplies the (already removed) block as a parameter.

**Comment by superstorm192** [comment]
That's good to know. If it is called __BEFORE__, there is at least one way to determine what block would have gone there if it was placed. `m.GetInventory(player).RightHand[m.GetActiveMaterialSlot(player)];`

**Comment by superstorm192** [comment]
```
bool CheckOnDelete2(int player, int x, int y, int z)
{
    m.SendMessage(player, m.GetBlockNameAt(x,y,z));
    return false;
}
```
This piece of code(as you said) does return the block that __WAS__ there, but I am still wondering why the block flickers, shouldn't the block just not flicker at all?

**Comment by croxxx** [comment]
The client removes the block locally and then gets feedback from the server to revert the change.
