### ISSUE TITLE
Text rendering bugs

### ISSUE THREAD

**Issue by croxxx** [manicdigger/manicdigger#242]
There has been a subtle bug affecting text rendering for quite some time now.
Most of the time things work, but especially when centering or right-aligning text the issue pops up.

In order to track down what is going wrong I implemented the drawing of text bounding boxes for texts in 02dddf6d62bd770321ea1f44ff2fe46a4c1c2167 today.

The bug is caused by seemingly incorrect calculation of text width. Some screenshots of the problem are attached. Green boxes are rendered text size, yellow boxes depict used texture size.
1. Main menu on windows. Note the differences between right-aligned labels (green boxes)  
   ![mainmenu-align-right](https://cloud.githubusercontent.com/assets/5447834/13472697/546293a0-e0b6-11e5-86e0-5f262e60e2d9.png)
2. Playerlist generated by a Linux server displayed on a Windows machine  
   ![playerlist-linux-win](https://cloud.githubusercontent.com/assets/5447834/13472693/53016d9c-e0b6-11e5-99d6-777a2451154b.png)
3. Playerlist generated by a Windows server displayed on a Windows machine  
   ![playerlist-win-win](https://cloud.githubusercontent.com/assets/5447834/13472696/545bf1a8-e0b6-11e5-887c-d320e8832ccd.png)

I tried to nail this bug down for 4 hours today and really don't know what else to check. So if anyone finds something I missed that would be a great help.
### Things found so far:
- The text bounding boxes drawn in the renderer seem just fine. Those are visible as green lines in the pictures.
- Regardless of actual texture size textures seem to be cut off on the right side sometimes. This can be seen happening in above screenshots as well.
- All text measurement calls via `GamePlatform` interface always use `Verdana` as font family ([TextRenderer.cs](https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/ClientNative/TextRenderer.cs#L210))
- Changing all font families used in the game to either `Arial` or `Verdana` does not fix the issue. Instead it gets worse for whatever reason.
- Calculation of colored text part lengths contains code that could accumulate errors ([GameMisc.ci.cs](https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/Client/Misc/GameMisc.ci.cs#L1842)). Replacing it with the same call that is used for measurement in rendering did not help, though.
- **Just noticed but not yet confirmed:** `PlayerList.cs` defined font size as 8 for some fonts ([PlayerList.cs](https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/Server/Mods/Fortress/PlayerList.cs#L183)). In game code I found passages forcing size to be 9 minimum ([TextRenderer.cs](https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/ClientNative/TextRenderer.cs#L210)).
  Might cause the displaced ping/page number.

**Comment by superstorm192** [comment]
Could this be related to text fonts and colors not working at all through the modding API? #231

**Comment by croxxx** [comment]
@superstorm192 No, that is caused by a different issue.

**Comment by croxxx** [comment]
Text rendering never actually uses the FontFamily or FontType properties when measuring text.
That results in incorrect results whenever a non-default font is to be rendered.

Corresponding code can be found in Platform interface, only available parameters in the function currently are text and font size:
https://github.com/manicdigger/manicdigger/blob/master/ManicDiggerLib/Client/Misc/PlatformNative.cs#L245
```csharp
public override void TextSize(string text, float fontSize, IntRef outWidth, IntRef outHeight)
{
    SizeF size = TextSize(text, fontSize);
    outWidth.value = (int)size.Width;
    outHeight.value = (int)size.Height;
}
```
Fixing font measurement therefore needs a minor rewrite of related functions to pass required parameters.

**Comment by croxxx** [comment]
Text rendering is fixed after a complete rework.
