### ISSUE TITLE
OnPlayerDisconnect() not called when server restarts or shuts down.

### ISSUE THREAD

**Issue by superstorm192** [manicdigger/manicdigger#244]
It would be reasonable for this to call the disconnect when the server restarts. Currently I am working on a CreativeZone mod for Survival, but if the server restarts, the player's disconnect is not called and another piece of code intervenes. In survival mode, all zeros (infinite blocks) gets saved as a single block (finite, but I don't want everyone to have one of every block. This is why I have an OnPlayerDisconnect() clearing all of those zeros. But this cannot work when it isn't even called on server restarts and crashes ~ okay crashes are fine because that's different.

**Comment by croxxx** [comment]
I have come across this myself and will change behaviour of the server to disconnect all players properly on a restart/shutdown.
