### ISSUE TITLE
Hi are any on orginal author /contributors still active?

### ISSUE THREAD

**Issue by AlexJustRandom** [manicdigger/manicdigger#254]
i was playing with this mad code base entire week and i have few questions.. can we talk?

**Comment by Nisc3d** [comment]
Try it on the Pixolia Discord Server: https://discord.gg/JqJxyK3S

**Comment by AlexJustRandom** [comment]
Hi ,I don't know if i left by accident or something else happened can i get invite again? @Nisc3d

**Comment by Nisc3d** [comment]
https://discord.com/invite/HetJ8ZerAT
