### ISSUE TITLE
Lag every second

### ISSUE THREAD

**Issue by exemd** [manicdigger/manicdigger#68]
Happens only sometimes.

![lag](https://cloud.githubusercontent.com/assets/5091290/2703507/cf51b366-c452-11e3-9577-ce3a18b4f9f7.png)

**Comment by croxxx** [comment]
Adressed in this commit: ee57945fe4daab6d9e2d77c1a9c13ec3dec6e19b
Will further observe this.

**Comment by croxxx** [comment]
Did not experience this anymore.
Closing as it has apparently been solved.
