### ISSUE TITLE
Water display issue

### ISSUE THREAD

**Issue by croxxx** [manicdigger/manicdigger#7]
Waterfalls have small gaps in between. Caused by block not being drawn as full height.
Add a check to TerrainChunkTesselator if block above is water, too.
If yes, draw full height.
![2014-01-24_19-51-01](https://f.cloud.github.com/assets/5447834/1997691/aebe4466-8528-11e3-81d8-c4aff8218512.png)

**Comment by TobiMob** [comment]
Looks a bit better now in [this branch](https://github.com/TobiMob/manicdigger/commit/431db1b3edaaaad0ff3e6ffcda1be110a8ec15cb)

![waterok](https://cloud.githubusercontent.com/assets/9436771/5636222/7658a2e0-95f0-11e4-8c4e-b3ee211b6645.png)

But if a waterblock is surrounded and the upper block is solid, the water block is still marked as not visible.
![waterfail](https://cloud.githubusercontent.com/assets/9436771/5636287/0588e3d0-95f1-11e4-9c51-d808c8e43d89.png)

I think to make this completly work, the CalculateVisibleFaces(...) needs to be modified. I will try that next.

**Comment by croxxx** [comment]
Should be fixed by #166
